apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: backend
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.azure.tenantId }}
  labels:
    azure.workload.identity/use: "true"