apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend-app
  ports:
    - name: http-frontend
      protocol: TCP
      port: 80
      targetPort: http-frontend