apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend-app
  ports:
    - name: http-frontend
      protocol: TCP
      port: 80
      targetPort: http-frontend

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - workplacevitalityhubstaging.nl
    secretName: tls-secret
  rules:
  - host: workplacevitalityhubstaging.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80
