name: CI WVH-Backend

on:
  push:
    paths:
      - smart-clicker-backend/**
      - .github/workflows/backend-ci.yml
  pull_request:
    paths:
      - smart-clicker-backend/**
      - .github/workflows/backend-ci.yml
  workflow_dispatch:

env:
  IMAGE_NAME: backend

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install backend npm dependencies
        run: cd smart-clicker-backend && npm install

      - name: Run ESLint
        run: cd smart-clicker-backend && npm run lint

  build:
    needs: lint
    name: Build backend
    strategy:
      matrix:
        # platform: [ubuntu-latest, windows-latest, macOS-latest]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install backend npm dependencies
        run: cd smart-clicker-backend && npm install

      - name: Create .env file
        run: |
          cd smart-clicker-backend
          touch .env
          echo "${{ secrets.BACKEND_ENV }}" > .env

      - name: Run build
        run: cd smart-clicker-backend && npm run build

      - name: Zip artifact for deployment
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: zip node-app.zip ./smart-clicker-backend/dist ./smart-clicker-backend/package.json ./smart-clicker-backend/package-lock.json ./smart-clicker-backend/.env ./smart-clicker-backend/swagger.json -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  test:
    needs: build
    name: Run Jest unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install backend npm dependencies
        run: cd smart-clicker-backend && npm install

      - name: Run unit tests
        run: |
          cd smart-clicker-backend 
          npm run test:coverage
          echo coverage/lcov.info

  sonarqube:
    needs: test
    name: SonarQube
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  deploy-container-staging:
    needs: test
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.event.pull_request.base.ref == 'staging'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT_STAGING }}
          username: ${{ secrets.ACR_USERNAME_STAGING }}
          password: ${{ secrets.ACR_PASSWORD_STAGING }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name : Debug
        run: ls -a

      - name: Unzip artifact for deployment
        run: unzip node-app.zip

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          # file: ./smart-clicker-backend/Dockerfile
          context: ./smart-clicker-backend
          build-args: |
            version=${{ github.sha }}
          tags: ${{ secrets.ACR_ENDPOINT_STAGING }}/${{ env.IMAGE_NAME }}:${{ github.sha}}
  
  deploy-container-main:
    needs: test
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT_PRODUCTION }}
          username: ${{ secrets.ACR_USERNAME_PRODUCTION }}
          password: ${{ secrets.ACR_PASSWORD_PRODUCTION }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip node-app.zip

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          # file: ./smart-clicker-backend/Dockerfile
          context: ./smart-clicker-backend
          build-args: |
            version=${{ github.sha }}
          tags: ${{ secrets.ACR_ENDPOINT_PRODUCTION }}/${{ env.IMAGE_NAME }}:${{ github.sha}}