name: CI WVH-Frontend

on:
  push:
    branches:
      - main
    paths:
      - smart-clicker-frontend/**
      - .github/workflows/frontend-ci.yml
  workflow_dispatch:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: [20.x]

      - name: Install frontend npm dependencies
        run: cd smart-clicker-frontend && npm install

      - name: Run ESLint
        run: cd smart-clicker-frontend && npm run lint

  build:
    needs: lint
    name: Build frontend
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: [20.x]

      - name: Install frontend npm dependencies
        run: cd smart-clicker-frontend && npm install

      - name: Create environment.ts file
        run: |
          cd smart-clicker-frontend/src
          mkdir environments
          cd environments
          touch environment.ts
          echo "${{ secrets.FRONTEND_ENV }}" > environment.ts

      - name: Run build
        run: cd smart-clicker-frontend && npm run build

  sonarqube:
    needs: build
    name: SonarQube
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}